spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 250708444412-re8ak675to0svc94vb6tntssmvmc6sbj.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  issuer: ajufresh@gmail.com
  secret_key: study-springboot

